kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: notesapp-http-scaler
spec:
  hosts:
    - notesapp.local
  pathPrefixes:
    - /
  scaleTargetRef:
    name: notesapp-fe
    kind: Deployment
    apiVersion: apps/v1
    service: notesapp-fe-service
    port: 80
  replicas:
    min: 1
    max: 10
  scaledownPeriod: 300
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 5
      window: 10s
