apiVersion: v1
kind: Service
metadata:
  name: myapp-database
spec:
  type: ClusterIP
  selector:
    app: myapp-database
  ports:
    - protocol: TCP
      port: { { .Values.database.servicePort } }
      targetPort: { { .Values.database.containerPort } }
