apiVersion: v1
kind: Service
metadata:
  name: myapp-frontend
spec:
  type: LoadBalancer
  selector:
    app: myapp-frontend
  ports:
    - protocol: TCP
      port: { { .Values.frontend.servicePort } }
      targetPort: { { .Values.frontend.containerPort } }
