apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
        - name: frontend
          image: { { .Values.frontend.image } }
          ports:
            - containerPort: { { .Values.frontend.containerPort } }
