kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: notesapp
  namespace: notesapp
spec:
  hosts:
    - notesapp.local
  pathPrefixes:
    - /api/
  scaleTargetRef:
    name: notesapp-be
    kind: Deployment
    apiVersion: apps/v1
    service: notesapp-be-service
    port: 8000
  replicas:
    min: 1
    max: 10
  scaledownPeriod: 30
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 5
      window: 10s
